workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - creds
      vars:
        XCODE_WORKSPACE: "kto.xcworkspace" # <----
        XCODE_SCHEME: "kto" # <----
        BUNDLE_ID: "org.main.kto" # <----
        APP_STORE_APP_ID: 6743850860 # <----
        APP_STORE_CONNECT_KEY_ID: "X84M4PFT62" # <----
        APP_STORE_CONNECT_ISSUER_ID: "6511ff0c-1b18-41bb-8cdb-e13a9a3c1ca5" # <----
        node: latest
        xcode: latest
        cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: yarn install
      - name: Install CocoaPods dependencies
        script: cd ios && pod install --repo-update
      - name: Set up keychain for code signing
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: keychain add-certificates
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Set up code signing settings in Xcode project
        script: xcode-project use-profiles --warn-only
      - name: Build IPA for distribution
        script: xcode-project build-ipa --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log # (якщо збірка тут логувалась)
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - build.log                   # <== основний лог, якщо пишеш `xcodebuild | tee build.log`
      - ios/build/**/*.log          # якщо вивід xcodebuild тут
      - ~/Library/Logs/DiagnosticReports/*.crash # Xcode crash reports
      - $HOME/Library/Developer/Xcode/DerivedData/**/*.log
      - $CM_BUILD_DIR/**/*.xcarchive # Повна архівація (для аналізу вручну)
      - $HOME/Library/Developer/Xcode/DerivedData/**/*.xcactivitylog # детальний лог компілятора
      - $HOME/Library/Logs/scan # якщо використовуєш `fastlane scan`
    publishing:
      email:
        recipients:
          - jameshutchinson1993@gmail.com       # <----
        notify:
          success: true
          failure: false
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: false
      app_store_connect:
        api_key: "$APP_STORE_CONNECT_PRIVATE_KEY"
        key_id: "$APP_STORE_CONNECT_KEY_ID"
        issuer_id: "$APP_STORE_CONNECT_ISSUER_ID"
        submit_to_testflight: true
